apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: service-types-demo
  labels:
    app: nginx
    component: web
    service-type: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginx
    component: web
  ports:
    - name: http
      port: 80
      targetPort: http
